In [1]:
#Convolution Neural Network

In [2]:
import keras

Using TensorFlow backend.


In [3]:
from keras.datasets import cifar10

In [7]:
(X_train,y_train),(X_test,y_test) = cifar10.load_data()

In [9]:
X_train.shape

(50000, 32, 32, 3)

In [10]:
X_train[1]

array([[[154, 177, 187],
        [126, 137, 136],
        [105, 104,  95],
        ..., 
        [ 91,  95,  71],
        [ 87,  90,  71],
        [ 79,  81,  70]],

       [[140, 160, 169],
        [145, 153, 154],
        [125, 125, 118],
        ..., 
        [ 96,  99,  78],
        [ 77,  80,  62],
        [ 71,  73,  61]],

       [[140, 155, 164],
        [139, 146, 149],
        [115, 115, 112],
        ..., 
        [ 79,  82,  64],
        [ 68,  70,  55],
        [ 67,  69,  55]],

       ..., 
       [[175, 167, 166],
        [156, 154, 160],
        [154, 160, 170],
        ..., 
        [ 42,  34,  36],
        [ 61,  53,  57],
        [ 93,  83,  91]],

       [[165, 154, 128],
        [156, 152, 130],
        [159, 161, 142],
        ..., 
        [103,  93,  96],
        [123, 114, 120],
        [131, 121, 131]],

       [[163, 148, 120],
        [158, 148, 122],
        [163, 156, 133],
        ..., 
        [143, 133, 139],
        [143, 134, 142],
        [143, 133,

In [11]:
X_train = X_train.astype('float32')

In [12]:
X_test = X_test.astype('float32')

In [13]:
X_train /= 255

In [14]:
X_test /= 255

In [15]:
y_train.shape

(50000, 1)

In [16]:
y_train[:5,]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [17]:
y_train = keras.utils.to_categorical(y_train,10)

In [18]:
y_test = keras.utils.to_categorical(y_test,10)

In [19]:
y_train.shape

(50000, 10)

In [20]:
y_train[:5,]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [21]:
from keras.models import Sequential

In [22]:
from keras.layers import Conv2D,Activation,MaxPooling2D,Dropout,Dense,Flatten

In [23]:
model = Sequential()

In [24]:
?Conv2D

In [ ]:
# Create the model with two 32 convolution filters -> pooling layer -> two 64 conv filters -> 
#pooling layer -> flattening -> fully conncted layer 
#adding convolution filter layer with 32 filters of size 3x3 to create features map,
#input_shape -> no . of neurons in input layer which is part of convolution layer ll be same as input image
#padding = dimension of feature map should be same as input image

In [25]:
model.add(Conv2D(32,(3,3),padding = 'same',input_shape = X_train.shape[1:]))

In [26]:
model.add(Activation('relu'))

In [27]:
?MaxPooling2D

In [28]:
model.add(MaxPooling2D((2,2),padding = 'same'))

In [29]:
model.add(Dropout(0.25))

In [30]:
model.add(Conv2D(64,(3,3),padding = 'same'))

In [31]:
model.add(Activation('relu'))

In [32]:
model.add(MaxPooling2D((2,2)))

In [33]:
model.add(Dropout(0.25))

In [34]:
model.add(Flatten())

In [35]:
model.add(Dense(kernel_initializer = 'uniform',units = 512,activation = 'relu'))

In [36]:
model.add(Dropout(0.5))

In [37]:
model.add(Dense(kernel_initializer = 'uniform',units = 10,activation = 'softmax'))

In [41]:
rmsoptimzer = keras.optimizers.rmsprop(lr = 0.0001,decay = 1e-6)

In [45]:
model.compile(optimizer = 'rmsprop',loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [46]:
model.fit(X_train,y_train,batch_size = 32,epochs = 20)

Epoch 1/20
50000/50000 [==============================] - 240s 5ms/step - loss: 1.4426 - acc: 0.4873
Epoch 2/20
50000/50000 [==============================] - 244s 5ms/step - loss: 1.1908 - acc: 0.5835
Epoch 3/20
50000/50000 [==============================] - 236s 5ms/step - loss: 1.1221 - acc: 0.6133
Epoch 4/20
50000/50000 [==============================] - 233s 5ms/step - loss: 1.1117 - acc: 0.6237
Epoch 5/20
50000/50000 [==============================] - 234s 5ms/step - loss: 1.1032 - acc: 0.6300
Epoch 6/20
50000/50000 [==============================] - 233s 5ms/step - loss: 1.1104 - acc: 0.6306
Epoch 7/20
50000/50000 [==============================] - 240s 5ms/step - loss: 1.1231 - acc: 0.6278
Epoch 8/20
50000/50000 [==============================] - 236s 5ms/step - loss: 1.1372 - acc: 0.6246
Epoch 9/20
50000/50000 [==============================] - 238s 5ms/step - loss: 1.1489 - acc: 0.6220
Epoch 10/20
50000/50000 [==============================] - 243s 5ms/step - loss: 1.1657 - a

In [53]:
preds = model.predict(X_test)

In [48]:
type(preds)

numpy.ndarray

In [49]:
preds.shape

(10000, 10)

In [61]:
preds[1:6,]

array([[  2.10028775e-02,   5.86290695e-02,   2.70344550e-04,
          1.61895077e-04,   1.00705211e-05,   2.91670985e-05,
          2.73427886e-05,   7.11735402e-06,   8.94909978e-01,
          2.49520242e-02],
       [  1.51417091e-01,   4.97639626e-02,   6.39059767e-02,
          1.00203402e-01,   5.48202805e-02,   5.94270565e-02,
          6.32935315e-02,   2.69462615e-02,   3.48368436e-01,
          8.18540007e-02],
       [  2.28933528e-01,   2.44911369e-02,   1.47682607e-01,
          4.86629829e-02,   6.56790584e-02,   2.59469710e-02,
          3.70111391e-02,   1.87178962e-02,   3.55807424e-01,
          4.70673554e-02],
       [  3.16140102e-03,   3.98617284e-03,   7.44916871e-02,
          5.98033741e-02,   4.33309466e-01,   2.29400899e-02,
          3.83326054e-01,   1.30196363e-02,   3.02942190e-03,
          2.93260626e-03],
       [  2.97895595e-02,   3.48772630e-02,   5.89570254e-02,
          1.13338336e-01,   1.52671441e-01,   6.26992583e-02,
          4.15288478e-01

In [55]:
y_test[1:6,]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.]])