In [1]:
import os

In [2]:
os.chdir('F:\\Library\\Analytics Path\\02-R\\02-R DataSets\\K means Clustering')

In [3]:
import pandas as pd

In [4]:
churnData = pd.read_csv('Churn Data.csv')

In [5]:
churnData.head()

state  account length  area code phone number international plan  \
0    KS             128        415     382-4657                 no   
1    OH             107        415     371-7191                 no   
2    NJ             137        415     358-1921                 no   
3    OH              84        408     375-9999                yes   
4    OK              75        415     330-6626                yes   

  voice mail plan  number vmail messages  total day minutes  total day calls  \
0             yes                     25              265.1              110   
1             yes                     26              161.6              123   
2              no                      0              243.4              114   
3              no                      0              299.4               71   
4              no                      0              166.7              113   

   total day charge  ...    total eve calls  total eve charge  \
0             45.07  ...                 99             16.78   
1             27.47  ...                103             16.62   
2             41.38  ...                110             10.30   
3             50.90  ...                 88              5.26   
4             28.34  ...                122             12.61   

   total night minutes  total night calls  total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total intl minutes  total intl calls  total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   customer service calls  churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False  

[5 rows x 21 columns]

In [6]:
del churnData['state']

In [7]:
del churnData['account length']

In [8]:
del churnData['phone number']

In [9]:
churnData.head()

area code international plan voice mail plan  number vmail messages  \
0        415                 no             yes                     25   
1        415                 no             yes                     26   
2        415                 no              no                      0   
3        408                yes              no                      0   
4        415                yes              no                      0   

   total day minutes  total day calls  total day charge  total eve minutes  \
0              265.1              110             45.07              197.4   
1              161.6              123             27.47              195.5   
2              243.4              114             41.38              121.2   
3              299.4               71             50.90               61.9   
4              166.7              113             28.34              148.3   

   total eve calls  total eve charge  total night minutes  total night calls  \
0               99             16.78                244.7                 91   
1              103             16.62                254.4                103   
2              110             10.30                162.6                104   
3               88              5.26                196.9                 89   
4              122             12.61                186.9                121   

   total night charge  total intl minutes  total intl calls  \
0               11.01                10.0                 3   
1               11.45                13.7                 3   
2                7.32                12.2                 5   
3                8.86                 6.6                 7   
4                8.41                10.1                 3   

   total intl charge  customer service calls  churn  
0               2.70                       1  False  
1               3.70                       1  False  
2               3.29                       0  False  
3               1.78                       2  False  
4               2.73                       3  False

In [10]:
churnData.shape

(3333, 18)

In [11]:
churnData['customer service calls'].value_counts()

1    1181
2     759
0     697
3     429
4     166
5      66
6      22
7       9
9       2
8       2
Name: customer service calls, dtype: int64

In [12]:
for i in range(len(churnData['customer service calls'])):
    if churnData['customer service calls'][i]>3:
        churnData['customer service calls'][i] = '>3'


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [13]:
churnData.head()

area code international plan voice mail plan  number vmail messages  \
0        415                 no             yes                     25   
1        415                 no             yes                     26   
2        415                 no              no                      0   
3        408                yes              no                      0   
4        415                yes              no                      0   

   total day minutes  total day calls  total day charge  total eve minutes  \
0              265.1              110             45.07              197.4   
1              161.6              123             27.47              195.5   
2              243.4              114             41.38              121.2   
3              299.4               71             50.90               61.9   
4              166.7              113             28.34              148.3   

   total eve calls  total eve charge  total night minutes  total night calls  \
0               99             16.78                244.7                 91   
1              103             16.62                254.4                103   
2              110             10.30                162.6                104   
3               88              5.26                196.9                 89   
4              122             12.61                186.9                121   

   total night charge  total intl minutes  total intl calls  \
0               11.01                10.0                 3   
1               11.45                13.7                 3   
2                7.32                12.2                 5   
3                8.86                 6.6                 7   
4                8.41                10.1                 3   

   total intl charge customer service calls  churn  
0               2.70                      1  False  
1               3.70                      1  False  
2               3.29                      0  False  
3               1.78                      2  False  
4               2.73                      3  False

In [14]:
churnData['customer service calls'].value_counts()

1     1181
2      759
0      697
3      429
>3     267
Name: customer service calls, dtype: int64

In [15]:
churnData.dtypes

area code                   int64
international plan         object
voice mail plan            object
number vmail messages       int64
total day minutes         float64
total day calls             int64
total day charge          float64
total eve minutes         float64
total eve calls             int64
total eve charge          float64
total night minutes       float64
total night calls           int64
total night charge        float64
total intl minutes        float64
total intl calls            int64
total intl charge         float64
customer service calls     object
churn                        bool
dtype: object

In [16]:
churnData.dtypes

area code                   int64
international plan         object
voice mail plan            object
number vmail messages       int64
total day minutes         float64
total day calls             int64
total day charge          float64
total eve minutes         float64
total eve calls             int64
total eve charge          float64
total night minutes       float64
total night calls           int64
total night charge        float64
total intl minutes        float64
total intl calls            int64
total intl charge         float64
customer service calls     object
churn                        bool
dtype: object

In [17]:
colsToObject = ['area code','churn']

In [18]:
for i in colsToObject:
    churnData[i] = churnData[i].astype('O')

In [19]:
churnData.dtypes

area code                  object
international plan         object
voice mail plan            object
number vmail messages       int64
total day minutes         float64
total day calls             int64
total day charge          float64
total eve minutes         float64
total eve calls             int64
total eve charge          float64
total night minutes       float64
total night calls           int64
total night charge        float64
total intl minutes        float64
total intl calls            int64
total intl charge         float64
customer service calls     object
churn                      object
dtype: object

In [20]:
colsToDummy = []
for i in churnData.columns:
    if churnData[i].dtype == 'O':
        colsToDummy.append(i)
        

In [21]:
churnData['area code'].dtype

dtype('O')

In [22]:
colsToDummy

['area code',
 'international plan',
 'voice mail plan',
 'customer service calls',
 'churn']

In [23]:
dummied_cols = pd.get_dummies(churnData[colsToDummy])

In [24]:
dummied_cols.head()

area code_408  area code_415  area code_510  international plan_no  \
0              0              1              0                      1   
1              0              1              0                      1   
2              0              1              0                      1   
3              1              0              0                      0   
4              0              1              0                      0   

   international plan_yes  voice mail plan_no  voice mail plan_yes  \
0                       0                   0                    1   
1                       0                   0                    1   
2                       0                   1                    0   
3                       1                   1                    0   
4                       1                   1                    0   

   customer service calls_0  customer service calls_1  \
0                         0                         1   
1                         0                         1   
2                         1                         0   
3                         0                         0   
4                         0                         0   

   customer service calls_2  customer service calls_3  \
0                         0                         0   
1                         0                         0   
2                         0                         0   
3                         1                         0   
4                         0                         1   

   customer service calls_>3  churn_False  churn_True  
0                          0            1           0  
1                          0            1           0  
2                          0            1           0  
3                          0            1           0  
4                          0            1           0

In [25]:
dummied_cols.columns

Index(['area code_408', 'area code_415', 'area code_510',
       'international plan_no', 'international plan_yes', 'voice mail plan_no',
       'voice mail plan_yes', 'customer service calls_0',
       'customer service calls_1', 'customer service calls_2',
       'customer service calls_3', 'customer service calls_>3', 'churn_False',
       'churn_True'],
      dtype='object')

In [26]:
del dummied_cols['area code_510']

In [27]:
del dummied_cols['international plan_no']

In [28]:
del dummied_cols['voice mail plan_no']

In [29]:
del dummied_cols['customer service calls_0']

In [30]:
del dummied_cols['churn_False']

In [31]:
dummied_cols.head()

area code_408  area code_415  international plan_yes  voice mail plan_yes  \
0              0              1                       0                    1   
1              0              1                       0                    1   
2              0              1                       0                    0   
3              1              0                       1                    0   
4              0              1                       1                    0   

   customer service calls_1  customer service calls_2  \
0                         1                         0   
1                         1                         0   
2                         0                         0   
3                         0                         1   
4                         0                         0   

   customer service calls_3  customer service calls_>3  churn_True  
0                         0                          0           0  
1                         0                          0           0  
2                         0                          0           0  
3                         0                          0           0  
4                         1                          0           0

In [32]:
churnData = churnData.drop(colsToDummy,axis = 1)

In [33]:
churnData = churnData.join(dummied_cols)

In [34]:
churnData.head()

number vmail messages  total day minutes  total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   total day charge  total eve minutes  total eve calls  total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   total night minutes  total night calls  total night charge     ...      \
0                244.7                 91               11.01     ...       
1                254.4                103               11.45     ...       
2                162.6                104                7.32     ...       
3                196.9                 89                8.86     ...       
4                186.9                121                8.41     ...       

   total intl charge  area code_408  area code_415  international plan_yes  \
0               2.70              0              1                       0   
1               3.70              0              1                       0   
2               3.29              0              1                       0   
3               1.78              1              0                       1   
4               2.73              0              1                       1   

   voice mail plan_yes  customer service calls_1  customer service calls_2  \
0                    1                         1                         0   
1                    1                         1                         0   
2                    0                         0                         0   
3                    0                         0                         1   
4                    0                         0                         0   

   customer service calls_3  customer service calls_>3  churn_True  
0                         0                          0           0  
1                         0                          0           0  
2                         0                          0           0  
3                         0                          0           0  
4                         1                          0           0  

[5 rows x 22 columns]

In [35]:
X = churnData.iloc[:,0:21]

In [36]:
y = churnData.iloc[:,21]

In [37]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: churn_True, dtype: uint8

In [38]:
from sklearn.model_selection import train_test_split

In [98]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 0)

In [40]:
from sklearn.ensemble import AdaBoostClassifier

In [122]:
?AdaBoostClassifier

In [42]:
classifier1 = AdaBoostClassifier(n_estimators  = 20)

In [43]:
classifier1 = classifier1.fit(X_train,y_train)

In [44]:
preds = classifier1.predict(X_test)

In [45]:
type(preds)

numpy.ndarray

In [47]:
preds[:6]

array([0, 0, 0, 0, 0, 0], dtype=uint8)

In [48]:
from sklearn.metrics import confusion_matrix

In [49]:
confusion_matrix(y_test,preds)

array([[687,  24],
       [ 85,  38]], dtype=int64)

In [52]:
38/(38+85)

0.3089430894308943

In [50]:
preds_train = classifier1.predict(X_train)

In [51]:
confusion_matrix(y_train,preds_train)

array([[2076,   63],
       [ 224,  136]], dtype=int64)

In [53]:
136/(136+224)

0.37777777777777777

In [130]:
classifier3 = AdaBoostClassifier(n_estimators  = 100)

In [131]:
classifier3.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=100, random_state=None)

In [134]:
preds_test3 = classifier3.predict(X_test)

In [135]:
confusion_matrix(y_test,preds_test3)

array([[680,  39],
       [ 73,  42]], dtype=int64)

In [148]:
42/(42+73)

0.3652173913043478

In [ ]:
#Not much improvement in recall. Lets try GradientBoosting

In [123]:
from sklearn.ensemble import GradientBoostingClassifier

In [124]:
?GradientBoostingClassifier

In [149]:
gb1 = GradientBoostingClassifier(n_estimators = 100)

In [150]:
gb1.fit(X_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [151]:
gb_preds = gb1.predict(X_test)

In [152]:
confusion_matrix(y_test,gb_preds)

array([[705,  14],
       [ 23,  92]], dtype=int64)

In [153]:
92/(92+23)

0.8